BEGIN;
CREATE TABLE "order_order__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_created_order" datetime NOT NULL, "order_amount" integer NOT NULL, "order_date" date NOT NULL, "order_customer_id_id" integer NOT NULL REFERENCES "order_customer" ("id"), "order_product_id_id" integer NOT NULL REFERENCES "order_product" ("id"));
INSERT INTO "order_order__new" ("order_amount", "id", "date_created_order", "order_customer_id_id", "order_date", "order_product_id_id") SELECT "order_amount", "id", '2015-02-09 20:55:55.628344', "order_customer_id_id", "order_date", "order_product_id_id" FROM "order_order";
DROP TABLE "order_order";
ALTER TABLE "order_order__new" RENAME TO "order_order";
CREATE INDEX "order_order_e89d72db" ON "order_order" ("order_customer_id_id");
CREATE INDEX "order_order_72978deb" ON "order_order" ("order_product_id_id");
CREATE TABLE "order_order__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "order_amount" integer NOT NULL, "order_date" date NOT NULL, "order_customer_id_id" integer NOT NULL REFERENCES "order_customer" ("id"), "order_product_id_id" integer NOT NULL REFERENCES "order_product" ("id"), "date_created_order" datetime NOT NULL, "date_updated_order" datetime NOT NULL);
INSERT INTO "order_order__new" ("order_amount", "id", "date_created_order", "order_customer_id_id", "order_date", "date_updated_order", "order_product_id_id") SELECT "order_amount", "id", "date_created_order", "order_customer_id_id", "order_date", '2015-02-09 20:56:00.285274', "order_product_id_id" FROM "order_order";
DROP TABLE "order_order";
ALTER TABLE "order_order__new" RENAME TO "order_order";
CREATE INDEX "order_order_e89d72db" ON "order_order" ("order_customer_id_id");
CREATE INDEX "order_order_72978deb" ON "order_order" ("order_product_id_id");
CREATE TABLE "order_product__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "product_name" varchar(128) NULL, "product_price" decimal NOT NULL, "product_type" varchar(128) NULL, "product_description" text NOT NULL, "date_created_product" datetime NOT NULL);
INSERT INTO "order_product__new" ("product_description", "id", "date_created_product", "product_type", "product_price", "product_name") SELECT "product_description", "id", '2015-02-09 20:56:05.772704', "product_type", "product_price", "product_name" FROM "order_product";
DROP TABLE "order_product";
ALTER TABLE "order_product__new" RENAME TO "order_product";
CREATE TABLE "order_product__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "product_name" varchar(128) NULL, "product_price" decimal NOT NULL, "product_type" varchar(128) NULL, "product_description" text NOT NULL, "date_created_product" datetime NOT NULL, "date_updated_product" datetime NOT NULL);
INSERT INTO "order_product__new" ("product_description", "id", "date_created_product", "product_type", "product_price", "date_updated_product", "product_name") SELECT "product_description", "id", "date_created_product", "product_type", "product_price", '2015-02-09 20:56:14.653165', "product_name" FROM "order_product";
DROP TABLE "order_product";
ALTER TABLE "order_product__new" RENAME TO "order_product";
CREATE TABLE "order_stock__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "stock_quantity" integer NOT NULL, "stock_product_id_id" integer NOT NULL REFERENCES "order_product" ("id"), "date_created_stock" datetime NOT NULL);
INSERT INTO "order_stock__new" ("stock_quantity", "stock_product_id_id", "id", "date_created_stock") SELECT "stock_quantity", "stock_product_id_id", "id", '2015-02-09 20:56:32.274936' FROM "order_stock";
DROP TABLE "order_stock";
ALTER TABLE "order_stock__new" RENAME TO "order_stock";
CREATE INDEX "order_stock_7ddac4af" ON "order_stock" ("stock_product_id_id");
CREATE TABLE "order_stock__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "stock_quantity" integer NOT NULL, "stock_product_id_id" integer NOT NULL REFERENCES "order_product" ("id"), "date_created_stock" datetime NOT NULL, "date_updated_stock" datetime NOT NULL);
INSERT INTO "order_stock__new" ("stock_quantity", "stock_product_id_id", "id", "date_created_stock", "date_updated_stock") SELECT "stock_quantity", "stock_product_id_id", "id", "date_created_stock", '2015-02-09 20:56:37.429491' FROM "order_stock";
DROP TABLE "order_stock";
ALTER TABLE "order_stock__new" RENAME TO "order_stock";
CREATE INDEX "order_stock_7ddac4af" ON "order_stock" ("stock_product_id_id");

COMMIT;
